In [12]:
import torch

In [13]:
import torch.nn as nn

In [14]:
x_data = torch.Tensor([
    [0,0],
    [1,0],
    [1,1],
    [0,0],
    [0,0],
    [0,1]
])

In [15]:
y_data = torch.LongTensor([
    0, # etc
    1, # mammal
    2, # birds
    0,
    0,
    2
])

In [16]:
class DNN(nn.Module):
    def __init__(self):
        super(DNN, self).__init__()
        self.w1 = nn.Linear(2, 10)
        self.bias1 = torch.zeros([10])

        self.w2 = nn.Linear(10, 3)
        self.bias2 = torch.zeros([3])
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=0)

    def forward(self, x):
        y = self.w1(x) + self.bias1
        y = self.relu(y)

        y = self.w2(y) + self.bias2
        return y

In [17]:
model = DNN()

In [18]:
criterion = torch.nn.CrossEntropyLoss() #손실함수

In [19]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [21]:
for epoch in range(1000):
    output = model(x_data)
    print(output)
    loss = criterion(output, y_data)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print("progress:", epoch, "loss=", loss.item())

tensor([[ 1.6055, -0.9689, -0.3881],
        [-0.4583,  0.3857,  0.3464],
        [-1.9124,  0.1971,  2.2112],
        [ 1.6055, -0.9689, -0.3881],
        [ 1.6055, -0.9689, -0.3881],
        [-0.0201, -1.1072,  1.6573]], grad_fn=<AddBackward0>)
progress: 0 loss= 0.3020242154598236
tensor([[ 1.6068, -0.9702, -0.3883],
        [-0.4590,  0.3859,  0.3468],
        [-1.9146,  0.1969,  2.2134],
        [ 1.6068, -0.9702, -0.3883],
        [ 1.6068, -0.9702, -0.3883],
        [-0.0212, -1.1082,  1.6593]], grad_fn=<AddBackward0>)
progress: 1 loss= 0.30169597268104553
tensor([[ 1.6080, -0.9702, -0.3895],
        [-0.4594,  0.3876,  0.3457],
        [-1.9172,  0.1993,  2.2142],
        [ 1.6080, -0.9702, -0.3895],
        [ 1.6080, -0.9702, -0.3895],
        [-0.0215, -1.1081,  1.6598]], grad_fn=<AddBackward0>)
progress: 2 loss= 0.3012702763080597
tensor([[ 1.6094, -0.9715, -0.3898],
        [-0.4601,  0.3877,  0.3461],
        [-1.9194,  0.1991,  2.2165],
        [ 1.6094, -0.9715, -0.3898],

tensor([[ 2.0742, -1.2044, -0.6548],
        [-0.7388,  0.7904,  0.2205],
        [-2.9219,  0.6491,  2.8605],
        [ 2.0742, -1.2044, -0.6548],
        [ 2.0742, -1.2044, -0.6548],
        [-0.3183, -1.3012,  2.1886]], grad_fn=<AddBackward0>)
progress: 448 loss= 0.18080486357212067
tensor([[ 2.0745, -1.2040, -0.6558],
        [-0.7396,  0.7923,  0.2195],
        [-2.9243,  0.6515,  2.8603],
        [ 2.0745, -1.2040, -0.6558],
        [ 2.0745, -1.2040, -0.6558],
        [-0.3186, -1.3010,  2.1886]], grad_fn=<AddBackward0>)
progress: 449 loss= 0.18059693276882172
tensor([[ 2.0760, -1.2051, -0.6562],
        [-0.7400,  0.7924,  0.2197],
        [-2.9258,  0.6512,  2.8623],
        [ 2.0760, -1.2051, -0.6562],
        [ 2.0760, -1.2051, -0.6562],
        [-0.3192, -1.3020,  2.1902]], grad_fn=<AddBackward0>)
progress: 450 loss= 0.18041370809078217
tensor([[ 2.0756, -1.2046, -0.6564],
        [-0.7420,  0.7942,  0.2198],
        [-2.9298,  0.6537,  2.8641],
        [ 2.0756, -1.2046, -

tensor([[ 2.4174, -1.3708, -0.8454],
        [-0.9825,  1.1599,  0.1017],
        [-3.6799,  0.9543,  3.3819],
        [ 2.4174, -1.3708, -0.8454],
        [ 2.4174, -1.3708, -0.8454],
        [-0.4988, -1.5467,  2.6609]], grad_fn=<AddBackward0>)
progress: 907 loss= 0.11666832119226456
tensor([[ 2.4186, -1.3716, -0.8459],
        [-0.9826,  1.1599,  0.1015],
        [-3.6805,  0.9539,  3.3825],
        [ 2.4186, -1.3716, -0.8459],
        [ 2.4186, -1.3716, -0.8459],
        [-0.4989, -1.5477,  2.6618]], grad_fn=<AddBackward0>)
progress: 908 loss= 0.11658170074224472
tensor([[ 2.4181, -1.3711, -0.8460],
        [-0.9843,  1.1616,  0.1015],
        [-3.6837,  0.9558,  3.3842],
        [ 2.4181, -1.3711, -0.8460],
        [ 2.4181, -1.3711, -0.8460],
        [-0.5003, -1.5475,  2.6633]], grad_fn=<AddBackward0>)
progress: 909 loss= 0.11646430939435959
tensor([[ 2.4197, -1.3721, -0.8465],
        [-0.9836,  1.1615,  0.1011],
        [-3.6834,  0.9550,  3.3851],
        [ 2.4197, -1.3721, -

In [10]:
PATH = './weights/'

torch.save(model, 'model.pt')  # 전체 모델 저장
torch.save(model.state_dict(), 'model_state_dict.pt')  # 모델 객체의 state_dict 저장
torch.save({
    'model': model.state_dict(),
    'optimizer': optimizer.state_dict()
}, 'all.tar')  